### ISSUE TITLE
Install is confusing

### ISSUE THREAD

**Issue by iqbal-lab** [sgearle/bugwas#1]
There is no tar.gz to download, but the README says

To install this package in R:
install.packages("[some_dir]/bugwas_1.0.tar.gz", repos = NULL, type="source")

**Comment by jessiewu** [comment]
Hi Zam,

Thanks for flagging that. The bugwas_1.0.tar.gz file is in the build folder of this repository. I have added that information in the README.

Jessie

**Comment by iqbal-lab** [comment]
Thanks!
