### ISSUE TITLE
Some issues in using the function get_gen_var

### ISSUE THREAD

**Issue by wanyuac** [sgearle/bugwas#7]
**1. An error of unmatched sample names between the SNP data and the variant data**

`
Error in get_gen_var(var.matrix = var.matrix, XX.ID = XX.ID, logreg.var = logreg.var,  :
Error: Sample names of SNP data do not match the sample names of variant data
`

This error arises when any sample names in the variant data are comprised of digits only. In the code:

`
gen.var <- read.table(var.matrix[iGenVar], header=T, sep="\t")
`
the check.names is TRUE by default. Hence R adds an "X" to every sample name that consists of only digits to make a valid column name.

This problem does not happen on the SNP data because in the function get_SNP_data, SNPs are read through

`
XX <- read.table(gen,header=T,sep="\t",as.is=T, check.names = F)
`
hence XX.ID may contain sample names of pure digits.

In summary, I would suggest to read the variant data through:

`
gen.var <- read.table(var.matrix[iGenVar], header=T, sep="\t",as.is=T, check.names = F)
`
or inform users not to provide any digital sample names.

**2. the argument gem.path is not defined in the function**

Error message:
`
Error in paste0(path, " -g ", gen.output.file, " -p ", pheno.file, " -a ",  : object 'gem.path' not found
`

Because the function get_gen_var is defined as:
`
get_gen_var <- function(var.matrix = NULL,
						XX.ID = NULL,
						logreg.var = NULL,
						lmm.var = NULL,
						relmatrix = NULL,
						pheno.file = NULL,
						maf = NULL,
						prefix = NULL,
						path = NULL,
						dir = NULL,
						run.lmm = NULL,
						pca = NULL,
						npcs = NULL){
`

The run_lmm_bi function cannot be called via:

`
lmm.gen.var <- run_lmm_bi(XX = genVarList[[iGenVar]]$gen.var$var, relmatrix = relmatrix, 
									  pattern = genVarList[[iGenVar]]$gen.var$pattern, 
									  ps = var_ps, pheno.file = pheno.file, 
									  maf = maf, prefix = paste0(prefix, "_var"), 
path = gem.path, dir = output.dir)
`

**3. output.dir is not defined inside the function either**

The cause is the same as the gem.path. Maybe we can fix problems (2) and (3) through changing the argument list of get_gen_var into:
`
get_gen_var <- function(var.matrix = NULL,
						XX.ID = NULL,
						logreg.var = NULL,
						lmm.var = NULL,
						relmatrix = NULL,
						pheno.file = NULL,
						maf = NULL,
						prefix = NULL,
						gem.path = NULL,
						output.dir = NULL,
						run.lmm = NULL,
						pca = NULL,
						npcs = NULL){
`

Thanks.

**Comment by sgearle** [comment]
Thanks for flagging these issues, they have now been addressed.
