### ISSUE TITLE
bugwas question

### ISSUE THREAD

**Issue by ycgong** [sgearle/bugwas#8]
Running the example data with lin_loc it returns an error line and doesn't finish:

> data <- lin_loc(gen = gen, pheno = pheno, phylo = phylo,prefix = prefix, gem.path = "./gemma")
Error in checkExistence(arg) : The file does not exist!

Tried to use a new version of gemma (0.94.1) and even link gemma to /usr/local/bin, but that didn't solve the problem.

**Comment by sgearle** [comment]
The gemma version used must be our modified version 0.93 which can be downloaded from the bugwas github repository in the gemma folder. The error received means that one of your input files doesn't exist.

**Comment by ycgong** [comment]
Thanks @sgearle it works.
